### PR TITLE
Fix some brokens links

### PR DESCRIPTION
**Pull request by Munksgaard**

### CODE REVIEW

**Comment by Munksgaard** [comment]
Bump :-)

**Comment by kipcole9** [comment]
Thanks for the ping, and for the PR. I'll push a new docs update this evening my time.

**Comment by kipcole9** [comment]
Ah, I don't need to push anything since is the repo readme. Should be all ok now. Thanks again.

🥳🥳🥳🥳🥳

**Comment by Munksgaard** [comment]
Thank you!

**Pull request merged**
